global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'hrapp'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.254.82.198:9100']
      - targets: ['54.154.157.9:9100']


rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']